server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: mission
          uri: http://localhost:8081
          predicates:
            - Path=/missions/** 
        - id: reward
          uri: http://localhost:8082
          predicates:
            - Path=/rewards/** 
        - id: wallet
          uri: http://localhost:8083
          predicates:
            - Path=/wallets/** 
        - id: gift
          uri: http://localhost:8084
          predicates:
            - Path=/gifts/** 
        - id: mypage
          uri: http://localhost:8085
          predicates:
            - Path=/mypages/**
        - id: payment
          uri: http://localhost:8086
          predicates:
            - Path=/accounts/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: mission
          uri: http://game-mission:8080
          predicates:
            - Path=/missions/** 
        - id: reward
          uri: http://game-reward:8080
          predicates:
            - Path=/rewards/** 
        - id: wallet
          uri: http://game-wallet:8080
          predicates:
            - Path=/wallets/** 
        - id: gift
          uri: http://game-gift:8080
          predicates:
            - Path=/gifts/** 
        - id: mypage
          uri: http://game-mypage:8080
          predicates:
            - Path=/mypages/**
        - id: payment
          uri: http://game-payment:8080
          predicates:
            - Path=/accounts/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
